version: "3"
services:
  node:
    container_name: TwiTomo-Server
    build: .
    volumes:
      - ./app:/app
    tty: true
    ports:
      - 3000:3000
  db:
    image: postgres
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=1234
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
