version: "3"
services:
  node:
    container_name: TwiTomo-Server
    build: .
    volumes:
      - ./app:/app
    tty: true
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - 5432:5432