version: "3"
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./certs:/etc/nginx/ssl
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  node:
    container_name: TwiTomo-Server
    build: .
    volumes:
      - ./app:/app
    tty: true
    expose:
      - 4000
    ports:
      - 4000:4000
    command: sh -c "yarn start"
  db:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_DB: test
        POSTGRES_PASSWORD: admin