version: "3"
services:
  node:
    container_name: TwiTomo-Server
    build: .
    volumes:
      - ./app:/app
    tty: true
    ports:
      - 3000:3000
  db:
    image: postgres:11-alpine
    ports:
      - 5433:5432
    environment:
        POSTGRES_USER: admin
        POSTGRES_DB: test
        POSTGRES_PASSWORD: admin